# Generated by Django 5.0.6 on 2024-05-08 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boxmanagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="transfer",
            unique_together=set(),
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("num_boxes", models.PositiveIntegerField(default=0)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the inventory",
                        null=True,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="boxmanagement.station",
                    ),
                ),
            ],
            options={
                "get_latest_by": ["timestamp"],
            },
        ),
    ]
